/*----------------<(ACTION TYPES FOR CONFIGURATION)>----------------*/

export const FETCH_CONFIG_FINISHED = 'FETCH_CONFIG_FINISHED';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

/*----------------<(ACTION TYPES FOR LANGUAGE)>----------------*/

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const APPLY_LANGUAGE = 'APPLY_LANGUAGE';

/*----------------<(ACTION TYPES FOR OVERLAY LOADING)>----------------*/

export const START_OVERLAY_LOADING = 'START_OVERLAY_LOADING';
export const STOP_OVERLAY_LOADING = 'STOP_OVERLAY_LOADING';




/*----------------<(ACTION TYPES FOR HOME)>----------------*/

export const FETCHING_HOME_LAYOUT = 'FETCHING_HOME_LAYOUT';
export const FETCH_HOME_LAYOUT_SUCCESS = 'FETCH_HOME_LAYOUT_SUCCESS';
export const FETCH_HOME_LAYOUT_FAIL = 'FETCH_HOME_LAYOUT_FAIL';



//AUTHENTICATION
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOADING_AUTH = 'LOADING_AUTH';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//FORGET PASSWORD 

export const FORGET_SUCCESS = "FORGET_SUCCESS";


/*----------------<(ACTION TYPES FOR INTERNET STATUS)>----------------*/

export const UPDATE_INTERNET_STATUS = 'UPDATE_INTERNET_STATUS';


/*----------------<(ACTION TYPES FOR CATEGORY)>----------------*/


export const CHANGE_CATEGORY_LAYOUT = 'CHANGE_CATEGORY_LAYOUT';
export const INIT_CATEGORY_SCREEN = 'INIT_CATEGORY_SCREEN'
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = 'FETCH_CATEGORY_PRODUCTS_SUCCESS';
export const FETCH_CATEGORY_PRODUCTS_FAIL = 'FETCH_CATEGORY_PRODUCTS_FAIL';
export const TOGGLE_SORTING_MODAL = 'TOGGLE_SORTING_MODAL';
export const FETCH_ATTRIBUTES_SUCCESS = 'FETCH_ATTRIBUTES_SUCCESS';
export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCTS';
export const FETCH_MORE_PRODUCTS_SUCCESS = 'FETCH_MORE_PRODUCTS_SUCCESS';
export const FETCH_MORE_PRODUCTS_FAIL = 'FETCH_MORE_PRODUCTS_FAIL';
export const REFRESH_PRODUCTS = 'REFRESH_PRODUCTS';
export const APPLY_CATEGORY_FILTER = 'APPLY_CATEGORY_FILTER';
export const RESET_CATEGORY_SUCCESS = 'RESET_CATEGORY_SUCCESS';
export const ON_SORT_CATEGORY = 'ON_SORT_CATEGORY';

/*----------------<(ACTION TYPES FOR PRODUCT)>----------------*/

export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_FETCHING_SUCCESS = 'PRODUCT_FETCHING_SUCCESS';
export const PRODUCT_FETCHING_FAIL = 'PRODUCT_FETCHING_FAIL';

/*----------------<(ACTION TYPES FOR WISHLIST)>----------------*/

export const WISHLIST_FETCHING = 'WISHLIST_FETCHING';
export const WISHLIST_FETCHING_SUCCESS = 'WISHLIST_FETCHING_SUCCESS';
export const WISHLIST_FETCHING_FAIL = 'WISHLIST_FETCHING_SUCCESS';
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM';
export const EMPTY_WISHLIST = 'EMPTY_WISHLIST';
export const ADD_TO_LOCAL_WISHLIST = 'ADD_TO_LOCAL_WISHLIST';
export const REMOVE_FROM_LOCAL_WISHLIST = 'REMOVE_FROM_LOCAL_WISHLIST';
export const  EMPTY_LOCAL_WISHLIST = 'EMPTY_LOCAL_WISHLIST';

/*----------------<(ACTION TYPES FOR CART)>----------------*/

export const CART_FETCHING = 'CART_FETCHING';
export const CART_FETCHING_SUCCESS = 'CART_FETCHING_SUCCESS';
export const CART_FETCHING_FAIL = 'CART_FETCHING_FAIL';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const  CART_CHECKOUT_URL = 'CART_CHECKOUT_URL';
export const ADD_TO_LOCAL_CART = 'ADD_TO_LOCAL_CART';
export const DELETE_FROM_LOCAL_CART = 'DELETE_FROM_LOCAL_CART';
export const INC_LOCAL_CART = 'INC_LOCAL_CART';
export const DEC_LOCAL_CART = 'DEC_LOCAL_CART';
export const EMPTY_LOCAL_CART = 'EMPTY_LOCAL_CART';
export const CHANGE_CHECKOUT_TITLE = 'CHANGE_CHECKOUT_TITLE';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

/*----------------<(ACTION TYPES FOR SEARCH)>----------------*/
export const SEARCH_CHANGE_TEXT = 'SEARCH_CHANGE_TEXT';
export const SEARCH_FETCHING = 'SEARCH_FETCHING';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SEARCH_FETCHING_SUCCESS = 'SEARCH_FETCHING_SUCCESS';
export const SEARCH_FETCHING_FAIL = 'SEARCH_FETCHING_FAIL';

/*----------------<(ACTION TYPES FOR ADDRESSES)>----------------*/

export const ADDRESSES_FETCHING = 'ADDRESSES_FETCHING';
export const ADDRESSES_FETCHING_SUCCESS = 'ADDRESSES_FETCHING_SUCCESS';
export const REGIONS_FETCHING_SUCCESS = 'REGIONS_FETCHING_SUCCESS';
export const ADDRESSES_FETCHING_FAIL = 'ADDRESSES_FETCHING_FAIL';
export const ADDRESSES_REMOVE_ADDRESS = 'ADDRESSES_REMOVE_ADDRESS';


/*----------------<(ACTION TYPES FOR TOAST)>----------------*/
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';



/*----------------<(ACTION TYPES FOR REVIEWS)>----------------*/

export const REVIEWS_FETCHING = 'REVIEWS_FETCHING';
export const REVIEWS_FETCHING_SUCCESS = 'REVIEWS_FETCHING_SUCCESS';
export const REVIEWS_FETCHING_FAIL = 'REVIEWS_FETCHING_FAIL';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';

/*----------------<(ACTION TYPES FOR ORDER)>----------------*/

export const ORDERES_FETCHING_SUCCESS = "ORDERES_FETCHING_SUCCESS";
export const ORDERES_FETCHING_FAIL = "ORDERES_FETCHING_FAIL";
export const ORDERES_DETAILS_SUCCESS = "ORDERES_DETAILS_SUCCESS";
export const ORDERES_DETAILS_FAIL = "ORDERES_DETAILS_FAIL";
export const ORDERES_CANCEL_SUCCESS = "ORDERES_CANCEL_SUCCESS";
export const ORDERES_CANCEL_FAIL = "ORDERES_CANCEL_FAIL"