import { Platform } from 'react-native';


export const ICONS = {
    heart_outline: "heart-outline",
    menu:"menu",
    email : "email",
    lock : "lock",
    home : "home",
    heart_filled: "heart",
    share: "share-variant",
    cart: "cart",
    cartPlus: "cart-plus",
    listMode: "view-sequential",
    gridMode: "view-parallel",
    search: 'magnify',
    dotVertical: "dots-vertical",
    dotHorizontal: "dots-horizontal",
    close: 'close',
    eye: 'eye',
    eyeOff: 'eye-off',
    profile: 'account',
    myOrders: 'basket',
    myAddress: 'home',
    order: "package-variant",
    settings: "settings",
    backLeft: Platform.OS == 'ios' ? 'chevron-left' : "arrow-left",
    backRight: Platform.OS == 'ios' ? 'chevron-right' : "arrow-right",
    RightArrow: "chevron-right",
    LeftArrow: "chevron-left",
    addReview: "comment-text-multiple-outline",
    addNewReview: "tooltip-outline-plus",
    delete: "delete",
    unchecked: "radiobox-blank",
    checked: "check-circle",
    map_marker: "map-marker",
    phone: "cellphone-iphone",
    addAddress: "map-marker-plus",
    language: "web",
    filter: "filter",
    sorting: 'sort',
    approved: 'shopping',
    Processing: "progress-clock",
    Shipping: "truck",
    delivered: "check-circle",
    down: "chevron-down",
    up: "chevron-up",
    plus: "plus",
    minus: "minus",
    logout: "logout",
    pen: "pencil",
    basket: 'basket',
    shop:'shopify',
    shopping:'shopping',
    bell : "bell",
    shop: 'shopify',
    shopping: 'shopping',
    camera: 'camera',
    reset : "restore"
}